"""
Django settings for doctor_appointments project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u&b&!$@!2en$5z2tkyit_&s(h^x7=0vt2tz9x^g+npsq04evfy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_REDIRECT_URL = 'home'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'appointments/static'),
]


# Application definition

INSTALLED_APPS = [
    # Default Django apps...
    'django.contrib.sites',  # Required for django-allauth

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appointments',
    'rest_framework',
    'corsheaders',
    'modeltranslation',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware', 
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'doctor_appointments.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'doctor_appointments.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'study_user',
        'USER': 'mihnea.encean',
        'PASSWORD': 'zm.mnx.csro',
        'HOST': '13.60.249.153',  # Use the appropriate host
        'PORT': '3306',       # Default MySQL port
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RESET_LINK_BASE_URL = 'http://localhost:8000'

SESSION_COOKIE_AGE = 1209600

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:5555",
]

# RabbitMQ Broker URL (use 'guest' for default username/password if you didn't create a new user)
CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672//"

# Optional: Specify the result backend if needed (can also use Redis or database)
CELERY_RESULT_BACKEND = "rpc://"  # This stores results in RabbitMQ itself

# Task serialization format
CELERY_TASK_SERIALIZER = "json"

# Content types allowed
CELERY_ACCEPT_CONTENT = ["json"]

STRIPE_PUBLISHABLE_KEY = "pk_live_51QmXYuKKSSs4op9c0PzJ2WLpm1NDbR10gM0af0SeJCWB5WZEY0dq7sOTdV6VdL5qLOI9ccqB2maoJOvosQWftkic007GU0ldX1"  # Found in the Stripe Dashboard
STRIPE_SECRET_KEY = "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" 

LANGUAGE_CODE = 'en'  # Romanian as the default language
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('ro', 'Română'),
    ('en', 'English'),
    ('it', 'Italiano'),
    ('es', 'Español'),
    ('de', 'Deutsch'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

SITE_ID = 2

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # default
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # or 'mandatory' if you want verification
#ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGIN_METHODS = {'username', 'email'}

# settings.py

TWILIO_ACCOUNT_SID = "ACd94e4e09ac04c038287ab8c93c6c9954"
TWILIO_AUTH_TOKEN = "430d092a786113ba9ee42eb6b048cbe4"
TWILIO_PHONE_NUMBER = "(989) 447-8613"




