# Generated by Django 5.1.4 on 2024-12-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_availability_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
