# Generated by Django 5.1.4 on 2025-01-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='reserved',
            new_name='first_week_reserved',
        ),
        migrations.AddField(
            model_name='slot',
            name='second_week_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
