# Generated by Django 5.1.4 on 2025-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_rename_reserved_slot_first_week_reserved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('doctor_contact', models.CharField(max_length=15)),
                ('doctor_address', models.TextField()),
                ('doctor_clinic', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('one_time_only', models.BooleanField(default=False)),
                ('repeat_every', models.IntegerField(blank=True, help_text='Number of units to repeat', null=True)),
                ('unit', models.CharField(blank=True, choices=[('week', 'Week'), ('month', 'Month')], max_length=10, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('client_contact', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
