# Generated by Django 5.1.4 on 2025-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False, help_text='Indicates if the appointment is confirmed'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
