# Generated by Django 5.1.4 on 2025-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_appointment_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
