# Generated by Django 5.1.4 on 2025-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_client_latitude_client_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
