# Generated by Django 5.1.5 on 2025-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_remove_appointment_client_address_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
