# Generated by Django 5.1.5 on 2025-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0027_remove_doctor_city_remove_doctor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='test',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
