# Generated by Django 5.1.5 on 2025-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0028_client_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='test',
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
