# Generated by Django 5.1.5 on 2025-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0032_chatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='read_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='read_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
