# Generated by Django 5.1.5 on 2025-03-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0034_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctor'),
        ),
    ]
