# Generated by Django 5.1.5 on 2025-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0035_appointment_client_fk_appointment_doctor_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
