# Generated by Django 5.1.5 on 2025-03-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0036_alter_notificationsetting_push_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_fk',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_fk',
        ),
    ]
