# Generated by Django 5.1.5 on 2025-03-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0039_sitemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='push_auth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_endpoint',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_p256dh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
