# Generated by Django 5.1.5 on 2025-03-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0040_notificationsetting_push_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='font_family',
            field=models.CharField(default='Arial', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='font_size',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='font_weight',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
