# Generated by Django 5.1.5 on 2025-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0041_notificationsetting_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
