# Generated by Django 5.1.5 on 2025-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0042_notificationsetting_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('in_clinic', 'In Clinic'), ('online', 'Online')], default='in_clinic', max_length=20),
        ),
    ]
