# Generated by Django 5.1.5 on 2025-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0043_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='call_link',
            field=models.URLField(blank=True, help_text='Video call link for online appointments', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform',
            field=models.CharField(blank=True, help_text='Platform used for online appointments (e.g., Jitsi, Zoom)', max_length=50, null=True),
        ),
    ]
